const technologies = [
    { name: 'JavaScript', code: 'js' },
    { name: 'TypeScript', code: 'ts' },
    { name: 'React', code: 'react' },
    { name: 'Vue.js', code: 'vue' },
    { name: 'Node.js', code: 'node' },
    { name: 'Next.js', code: 'next' },
    { name: 'Nuxt.js', code: 'nuxt' },
    { name: 'Angular', code: 'angular' },
    { name: 'Svelte', code: 'svelte' },
    { name: 'Express.js', code: 'express' },
    { name: 'NestJS', code: 'nestjs' },
    { name: 'Electron', code: 'electron' },
    { name: 'Deno', code: 'deno' },
    { name: 'Fastify', code: 'fastify' },
    { name: 'Remix', code: 'remix' },
    { name: 'SolidJS', code: 'solid' },
    { name: 'Redux', code: 'redux' },
    { name: 'Zustand', code: 'zustand' },
    { name: 'Recoil', code: 'recoil' },
    { name: 'RxJS', code: 'rxjs' },
    { name: 'jQuery', code: 'jquery' },
    { name: 'Lodash', code: 'lodash' },
    { name: 'Tailwind CSS', code: 'tailwind' },
    { name: 'Bootstrap', code: 'bootstrap' },
    { name: 'Material UI', code: 'mui' },
    { name: 'Chakra UI', code: 'chakra' },
    { name: 'Ant Design', code: 'antd' },
    { name: 'Three.js', code: 'three' },
    { name: 'Chart.js', code: 'chartjs' },
    { name: 'D3.js', code: 'd3' },
    { name: 'TensorFlow.js', code: 'tfjs' },
    { name: 'GraphQL', code: 'graphql' },
    { name: 'Apollo', code: 'apollo' },
    { name: 'Prisma', code: 'prisma' },
    { name: 'MongoDB', code: 'mongodb' },
    { name: 'Mongoose', code: 'mongoose' },
    { name: 'PostgreSQL', code: 'postgres' },
    { name: 'MySQL', code: 'mysql' },
    { name: 'Firebase', code: 'firebase' },
    { name: 'Supabase', code: 'supabase' },
    { name: 'Docker', code: 'docker' },
    { name: 'Kubernetes', code: 'kubernetes' },
    { name: 'WebAssembly', code: 'wasm' },
    { name: 'Jest', code: 'jest' },
    { name: 'Cypress', code: 'cypress' },
    { name: 'Playwright', code: 'playwright' },
    { name: 'Vitest', code: 'vitest' },
    { name: 'Webpack', code: 'webpack' },
    { name: 'Vite', code: 'vite' },
    { name: 'Parcel', code: 'parcel' },
    { name: 'ESLint', code: 'eslint' },
    { name: 'Prettier', code: 'prettier' },
    { name: 'Husky', code: 'husky' },
];

export default technologies;
